spring:
  application:
    name: CONFIG-Dev
   
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Surendra10@gmail
    driver-class-name: com.mysql.cj.jdbc.Driver        
      
